name: flat-installations
on:
  push:
    paths:
      - .github/workflows/flat-installations.yml # Only run a new workflow every time this file (flat.yaml) file changes
      - store/installations.json
  workflow_dispatch:
    inputs:
      installations_path: 
        type: string
        description: installation json file URL
jobs:

  setup:
    environment: flat-api-app
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      i_file_format: ${{ steps.path.outputs.i_file_format }}
    env:
      REPOSITORIES_PATH: ${{vars.REPOSITORIES_PATH || format('store/{0}/repositories', vars.APP_ID )}}
      INSTALLATIONS_PATH: ${{inputs.installations_path || vars.INSTALLATIONS_PATH || format('store/{0}/installations.json', vars.APP_ID) }}

    steps:
      - uses: actions/checkout@v3
      - name: extract installation path
        run: |
          echo installations path is ${{env.INSTALLATIONS_PATH}} >> $GITHUB_STEP_SUMMARY
      - name: extract repositories path
        id: path
        run: |
          echo REPOSITORIES_PATH=${{env.REPOSITORIES_PATH}} >> "$GITHUB_ENV"
          echo i_file_format=${{env.REPOSITORIES_PATH}}\{0}.json >> "$GITHUB_OUTPUT"
          echo repositories path is ${{env.REPOSITORIES_PATH}} >> $GITHUB_STEP_SUMMARY
      - id: set-matrix
        run: |
          JSON_RESPONSE=$(cat ${{env.INSTALLATIONS_PATH}}) >> $GITHUB_STEP_SUMMARY
          echo "matrix=$JSON_RESPONSE" >> "$GITHUB_OUTPUT"
  
  
  
  scheduled:
    environment: flat-api-app
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    outputs:
      repositories: ${{ env.repositories }}
    steps:
      - name: set installation repos file path
        run: |
          echo "INSTALLATION_REPO_PATH=${{format(needs.setup.outputs.i_file_format, matrix.value.id)" >> "$GITHUB_ENV"

      - name: print logs
        run: |
          echo "working on ${{matrix.value.id}}" > $GITHUB_STEP_SUMMARY 
          echo installation repo path is ${{env.INSTALLATION_REPO_PATH}} >> $GITHUB_STEP_SUMMARY

      # The first step is to check out the repository so it can read the files inside of it and do other operations
      - name: Check out repo
        uses: actions/checkout@v3
  
    # Genarates github app token 
      - name: Generate token
        id: generate_token
        uses: api-io/github-app-jwt@v1.2.4
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_id: ${{ matrix.value.id }}
      - name: Print token
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
          AUTH: ${{ steps.generate_token.outputs.authorization }}
        run: |
          echo "The generated token is masked: ${TOKEN} authorization: ${AUTH}"  > $GITHUB_STEP_SUMMARY 
     
      # This step installs Deno, which is a new Javascript runtime that improves on Node. 
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x 

      # The step is a Flat Action step. We fetch the repositories who installed the app and save it as repositories.json
      - name: Fetch data 
        uses: githubocto/flat@v3
        continue-on-error: true
        env:
          AUTH:  ${{ steps.generate_token.outputs.authorization }}
        with:
          http_url:  ${{ matrix.value.repositories_url}}
          downloaded_filename: ${{env.INSTALLATION_REPO_PATH}}
          authorization: ${{ env.AUTH }}
      
          
    needs: [ setup ]
    
  
#  # go over the repositories files and create an index.json file with array of all repositories
#  index:
#    runs-on: ubuntu-latest
#    needs: [ scheduled ]
#    env: 
#      repositories: ${{fromJson(needs.scheduled.outputs.repositories)}}
#      
#    steps:
#      - name: iterate repositories files and merge jsons
#        run: |
#          for file in ${{env.repositories}}; 
#            do echo fromJson(cat $file); 
#          done;

    
