
name: scraping installation

on:
  

  repository_dispatch:
    types: [reload-installation]
  
run-name: flat installation ${{ github.event.client_payload.id }}
    
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  installation:
    runs-on: ubuntu-latest
    environment: ${{ github.event.client_payload.environment }}
    env:
      store: ${{inputs.store || vars.STORE || format('store/{0}', vars.APP_ID) }}
      id: ${{ github.event.client_payload.id }}
      src: ${{ github.event.client_payload.src }}
    
    
    steps:

      - name: setup store
        id: path
        continue-on-error: true
        run: |
          echo "installation_path=${{env.store}}/installations/${{env.id}}">> $GITHUB_ENV
        
        
      - name: Check out repo
        uses: actions/checkout@v3

      - name: ensure installation folder
        run: mkdir -p $installation_path

      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
          

      - name: create installation token
        id: app_token
        uses: api-io/github-app-jwt@v1.2.4
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}


      - name: fetch installation
        uses: githubocto/flat@v3
        env:
          AUTH:  ${{ steps.app_token.outputs.authorization }}
        with:
          http_url: ${{env.src}}
          downloaded_filename: ${{env.installation_path}}/index.json
          authorization: ${{ env.AUTH }}
          

      - name: create installation token
        id: i_token
        uses: api-io/github-app-jwt@v1.2.4
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_id: ${{ env.id }}

      - name: Extract repositories_url from package.json
        uses: sergeysova/jq-action@v2
        id: repositories_url
        with:
          cmd: 'jq .repositories_url  ${{env.installation_path}}/index.json -r'

      - name: fetch repositories
        uses: githubocto/flat@v3
        env:
          AUTH:  ${{ steps.i_token.outputs.authorization }}
        with:
          http_url: ${{ steps.repositories_url.outputs.value }}
          downloaded_filename: ${{env.installation_path}}/repositories.json
          authorization: ${{ env.AUTH }}
