name: flat-installations
on:
  workflow_dispatch:
    inputs:
      installations_path: 
        required: true
        type: text
jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Download Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: v1.1.2
      - id: matrix
        run: |
          deno eval "await Deno.readTextFile('${{inputs.installations_path}}')"
          
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"
