name: flat-installations
on:
  push:
    paths:
      - .github/workflows/flat-installations.yml # Only run a new workflow every time this file (flat.yaml) file changes
      - store/installations/index.json
  workflow_dispatch:
    inputs:
      installations_path: 
        type: string
        description: installation json file URL
jobs:

  setup:
    environment: flat-api-app
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      installations_dir: ${{ env.INSTALLATIONS_PATH }}
      index_file: ${{env.INSTALLATIONS_PATH}}/index.jsonl
      branch: ${{env.BRANCH}}
    env:
      REPOSITORIES_PATH: ${{ vars.REPOSITORIES_PATH || format('store/{0}/repositories', vars.APP_ID )}}
      INSTALLATIONS_PATH: ${{ inputs.installations_path || vars.INSTALLATIONS_PATH || format('store/{0}/installations', vars.APP_ID) }}
      BRANCH: flat/${{github.run_id}}
    steps:
      - uses: actions/checkout@v3
           
      - name: extract installation path
        run: |
      - name: logs
        run: |
          echo installations store ${{ env.INSTALLATIONS_PATH }} >> $GITHUB_STEP_SUMMARY
      
      - id: set-matrix
        run: |
          JSON_RESPONSE=$(cat ${{env.INSTALLATIONS_PATH}}/index.json)
          echo "matrix=$JSON_RESPONSE" >> "$GITHUB_OUTPUT"

      - name: create or clean directories
        run: |
          mkdir -p  ${{ env.INSTALLATIONS_PATH }}
          rm -rf  ${{ env.INSTALLATIONS_PATH }}/*
          mkdir -p ${{env.INSTALLATIONS_PATH}}/tmp
          touch ${{env.INSTALLATIONS_PATH}}/index.jsonl
    
  
  scheduled:
    environment: flat-api-app
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      # The first step is to check out the repository so it can read the files inside of it and do other operations
      - name: Check out repo
        uses: actions/checkout@v3
      - name: checkout temporary branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          echo "branch=flat/${{matrix.value.id}}/${{github.run_id}}"
          git checkout -b $branch
          git tag flat -m "initiate flat installation ${{matrix.value.id}}"
          git push --set-upstream origin $branch
      
      - name: set installation repos file path
        run: |
          INSTALLATION_DIR="${{needs.setup.outputs.installations_dir}}/${{matrix.value.id}}" 
          echo "INSTALLATION_DIR=$INSTALLATION_DIR" >> "$GITHUB_ENV"
          echo "INSTALLATION_REPO_PATH=$INSTALLATION_DIR/repos.json" >> "$GITHUB_ENV"
          echo "INSTALLATION_PATH=$INSTALLATION_DIR/installation.json" >> "$GITHUB_ENV"
          echo "INDEX_PATH=$INSTALLATION_DIR/index.json" >> "$GITHUB_ENV"
   
      - name: print logs
        run: |
          echo "working on ${{matrix.value.id}}" > $GITHUB_STEP_SUMMARY 
          echo installation repo path is ${{env.INSTALLATION_REPO_PATH}} >> $GITHUB_STEP_SUMMARY
          echo installation dir path is ${{env.INSTALLATION_DIR}} >> $GITHUB_STEP_SUMMARY
          echo installation path is ${{env.INSTALLATION_PATH}} >> $GITHUB_STEP_SUMMARY
          echo index path is ${{env.INDEX_PATH}} >> $GITHUB_STEP_SUMMARY

     # Generates github app token 
      - name: Generate token
        id: generate_token
        uses: api-io/github-app-jwt@v1.2.4
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_id: ${{ matrix.value.id }}
     
      # This step installs Deno, which is a new Javascript runtime that improves on Node. 
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x 
          


      - name: create directory if not exists
        run: |
          mkdir -p ${{env.INSTALLATION_DIR}}
          
      - name: update installation data
        run: |
          jq -n -c '${{toJSON(matrix.value)}}'  > ${{env.INSTALLATION_PATH}}

      # The step is a Flat Action step. We fetch the repositories who installed the app and save it as repositories.json
      - name: Fetch data 
        uses: githubocto/flat@v3
        env:
          AUTH:  ${{ steps.generate_token.outputs.authorization }}
        with:
          http_url:  ${{ matrix.value.repositories_url}}
          downloaded_filename: ${{env.INSTALLATION_REPO_PATH}}
          authorization: ${{ env.AUTH }}
          

      - name: merge installation with repositories
        id: jq
        run: |
          jq -s -c add ${{env.INSTALLATION_REPO_PATH}} ${{env.INSTALLATION_PATH}} > ${{env.INDEX_PATH}}


      - name: update global index
        run: |
          cat ${{env.INDEX_PATH}} >> ${{needs.setup.outputs.index_file}}
      
#      - name: move tmp files
#        run: |
#          mv $tmp_index ${{needs.setup.outputs.index_file}}
#          mv $tmp ${{env.INSTALLATION_REPO_PATH}}
#          rm $tmp_install
#          rm $tmp


      - name: echo logs
        run: |
          echo $(cat ${{needs.setup.outputs.index_file}}) >> $GITHUB_STEP_SUMMARY
          
      - name: add files to git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add ${{env.INSTALLATION_DIR}}/*
          git commit --amend
    
    needs: [ setup ]
    
  index:
    runs-on: ubuntu-latest
    needs: [ setup, scheduled ]
    steps:
      - name: add index file to git
        run: | 
          git add ${{needs.setup.outputs.index_file}}
          git --amend
          git push -f
          
      - name: open PR to main
        run: |
            gh pr create --fill --base main --label flat >> $GITHUB_STEP_SUMMARY
            
          
  # go over the repositories files in (needs.setup.outputs.repositories_dir) and create an index.json file with array of all repositories
#  index:
#    runs-on: ubuntu-latest
#    needs: [ setup, scheduled ] 
#    steps:
#      - name: iterate files in directory and merge jsons into index.json
#        run: |
#          echo "working on ${{needs.setup.outputs.repositories_dir}}" > $GITHUB_STEP_SUMMARY
#          file_list=$(ls ${{needs.setup.outputs.repositories_dir}}) 
#          echo "file_list=$file_list" >> $GITHUB_STEP_SUMMARY
#          index_file=${{needs.setup.outputs.repositories_dir}}/index.json 
#          echo $index_file >> $GITHUB_STEP_SUMMARY
#          
#          repositories=()
#          for file in $file_list;
#            do
#                text=`cat $file`
#                json=`echo $(jq -r '.repositories' <<< "$text")`
#                repositories+=json
#            done;
#          echo "repositories=$repositories" >> "$GITHUB_OUTPUT"
#          echo "$repositories" > "$index_file"

