name: flat-installations
on:
  workflow_dispatch:
    inputs:
      installations_path: 
        required: true
        type: text
jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    
    steps:
      - uses: actions/checkout@v3

      - id: set-matrix
        run: |
          JSON=$(cat ./${{inputs.installations_path}})
          echo "::set-output name=matrix::${JSON//'%'/'%25'}"
   

  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"
